<?php
/*** This app/http/BookingController.php file was generated by ProBot AI
 Date:4/1/2023 10:47:23 PM ***/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Booking;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class BookingController extends Controller{
	public function index(){
		$bookings = Booking::paginate(10);
		return view("pages.erp.booking.index",["bookings"=>$bookings]);
	}
	public function create(){
		return view("pages.erp.booking.create");
	}
	public function store(Request $request){
		//Booking::create($request->all());
		$booking = new Booking;
		$booking->name=$request->name;

		$booking->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$booking = Booking::find($id);
		return view("pages.erp.booking.show",["booking"=>$booking]);
	}
	public function edit(Booking $booking){
		return view("pages.erp.booking.edit",["booking"=>$booking]);
	}
	public function update(Request $request,Booking $booking){
		//Booking::update($request->all());
		$booking = Booking::find($booking->id);
		$booking->name=$request->name;

		$booking->save();

		return redirect()->route("bookings.index")->with('success','Updated Successfully.');
	}
	public function destroy(Booking $booking){
		$booking->delete();
		return redirect()->route("bookings.index")->with('success', 'Deleted Successfully.');
	}
}
?>
