<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_EmployeeController.php" was generated by ProBot AI.
* Date: 4/7/2023 12:19:12 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Employee;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class EmployeeController extends Controller{
	public function index(){
		$employees = Employee::paginate(10);
		return view("pages.erp.employee.index",["employees"=>$employees]);
	}
	public function create(){
		return view("pages.erp.employee.create",[]);
	}
	public function store(Request $request){
		//Employee::create($request->all());
		$employee = new Employee;
		$employee->name=$request->name;
		$employee->mobile=$request->mobile;
		$employee->email=$request->email;
date_default_timezone_set("Asia/Dhaka");
		$employee->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$employee->updated_at=date('Y-m-d H:i:s');

		$employee->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$employee = Employee::find($id);
		return view("pages.erp.employee.show",["employee"=>$employee]);
	}
	public function edit(Employee $employee){
		return view("pages.erp.employee.edit",["employee"=>$employee,]);
	}
	public function update(Request $request,Employee $employee){
		//Employee::update($request->all());
		$employee = Employee::find($employee->id);
		$employee->name=$request->name;
		$employee->mobile=$request->mobile;
		$employee->email=$request->email;
date_default_timezone_set("Asia/Dhaka");
		$employee->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$employee->updated_at=date('Y-m-d H:i:s');

		$employee->save();

		return redirect()->route("employees.index")->with('success','Updated Successfully.');
	}
	public function destroy(Employee $employee){
		$employee->delete();
		return redirect()->route("employees.index")->with('success', 'Deleted Successfully.');
	}
}
?>
