<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_MenuController.php" was generated by ProBot AI.
* Date: 4/15/2023 3:04:04 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Menu;
use App\Models\Category;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class MenuController extends Controller{
	public function index(){
		$menus = DB::table("menus as m")
		->join("categories as c","m.category_id","=","c.id")
		->select("m.id","m.name","m.price","c.name as category","m.photo","m.created_at","m.updated_at")
		->paginate(10);
		return view("pages.erp.menu.index",["menus"=>$menus]);
	}
	public function create(){
		return view("pages.erp.menu.create",["categories"=>Category::all()]);
	}
	public function store(Request $request){
		//Menu::create($request->all());
		$menu = new Menu;
		$menu->name=$request->name;
		$menu->price=$request->price;
		$menu->photo=$request->photo;
		$menu->category_id=$request->category_id;
		
date_default_timezone_set("Asia/Dhaka");
		$menu->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$menu->updated_at=date('Y-m-d H:i:s');

		$menu->save();
		

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$menu = Menu::find($id);
		return view("pages.erp.menu.show",["menu"=>$menu]);
	}
	public function edit(Menu $menu){
		return view("pages.erp.menu.edit",["menu"=>$menu,"categories"=>Category::all()]);
	}
	public function update(Request $request,Menu $menu){
		//Menu::update($request->all());
		$menu = Menu::find($menu->id);
		$menu->name=$request->name;
		$menu->price=$request->price;
		$menu->category_id=$request->category_id;
		if(isset($request->photo)){
			$menu->photo=$request->photo;
		}
date_default_timezone_set("Asia/Dhaka");
		$menu->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$menu->updated_at=date('Y-m-d H:i:s');

		$menu->save();
		if(isset($request->photo)){
			$imageName=$menu->id.'.'.$request->photo->extension();
			$menu->photo=$imageName;
			$menu->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return redirect()->route("menus.index")->with('success','Updated Successfully.');
	}
	public function destroy(Menu $menu){
		$menu->delete();
		return redirect()->route("menus.index")->with('success', 'Deleted Successfully.');
	}
	public function get_menu_json(){
        $id=$_GET["id"];     
        $request=Menu::find($id);
        return json_encode($request);
    }
}
?>
