<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_RawmaterialController.php" was generated by ProBot AI.
* Date: 4/7/2023 12:21:38 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Rawmaterial;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class RawmaterialController extends Controller{
	public function index(){
		$rawmaterials = Rawmaterial::paginate(10);
		return view("pages.erp.rawmaterial.index",["rawmaterials"=>$rawmaterials]);
	}
	public function create(){
		return view("pages.erp.rawmaterial.create",[]);
	}
	public function store(Request $request){
		//Rawmaterial::create($request->all());
		$rawmaterial = new Rawmaterial;
		$rawmaterial->name=$request->name;
		$rawmaterial->price=$request->price;
		$rawmaterial->measure=$request->measure;
		$rawmaterial->uom_name=$request->uom_name;
date_default_timezone_set("Asia/Dhaka");
		$rawmaterial->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$rawmaterial->updated_at=date('Y-m-d H:i:s');

		$rawmaterial->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$rawmaterial = Rawmaterial::find($id);
		return view("pages.erp.rawmaterial.show",["rawmaterial"=>$rawmaterial]);
	}
	public function edit(Rawmaterial $rawmaterial){
		return view("pages.erp.rawmaterial.edit",["rawmaterial"=>$rawmaterial,]);
	}
	public function update(Request $request,Rawmaterial $rawmaterial){
		//Rawmaterial::update($request->all());
		$rawmaterial = Rawmaterial::find($rawmaterial->id);
		$rawmaterial->name=$request->name;
		$rawmaterial->price=$request->price;
		$rawmaterial->measure=$request->measure;
		$rawmaterial->uom_name=$request->uom_name;
date_default_timezone_set("Asia/Dhaka");
		$rawmaterial->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$rawmaterial->updated_at=date('Y-m-d H:i:s');

		$rawmaterial->save();

		return redirect()->route("rawmaterials.index")->with('success','Updated Successfully.');
	}
	public function destroy(Rawmaterial $rawmaterial){
		$rawmaterial->delete();
		return redirect()->route("rawmaterials.index")->with('success', 'Deleted Successfully.');
	}
}
?>
